# Generated by Django 5.1.6 on 2025-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('followers', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SingerSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_singer', models.BigIntegerField()),
                ('id_song', models.BigIntegerField()),
            ],
        ),
    ]
