# Generated by Django 5.1.6 on 2025-03-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='singer',
            table='singer_singer',
        ),
        migrations.AlterModelTable(
            name='singersong',
            table='singer_singersong',
        ),
    ]
