# Generated by Django 5.1.6 on 2025-04-21 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0002_alter_singer_table_alter_singersong_table'),
        ('song', '0006_song_file_audio_song_file_video_song_url_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singersong',
            name='id_singer',
        ),
        migrations.RemoveField(
            model_name='singersong',
            name='id_song',
        ),
        migrations.AddField(
            model_name='singersong',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singer_songs', to='singer.singer'),
        ),
        migrations.AddField(
            model_name='singersong',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_singers', to='song.song'),
        ),
        migrations.AlterField(
            model_name='singersong',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]