# Generated by Django 5.1.6 on 2025-04-24 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0002_alter_singer_table_alter_singersong_table'),
        ('song', '0008_song_is_vip_alter_song_url_song_alter_song_url_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singersong',
            name='id_singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_song', to='singer.singer'),
        ),
        migrations.AlterField(
            model_name='singersong',
            name='id_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_singer', to='song.song'),
        ),
    ]
