# Generated by Django 5.1.6 on 2025-04-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0003_remove_singersong_id_singer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singersong',
            old_name='singer',
            new_name='id_singer',
        ),
        migrations.RenameField(
            model_name='singersong',
            old_name='song',
            new_name='id_song',
        ),
    ]