# Generated by Django 5.1.6 on 2025-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0006_alter_singersong_id_singer_alter_singersong_id_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singersong',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
