# Generated by Django 5.1.6 on 2025-03-31 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spotify_user', '0014_remove_userfollowing_user_follow_followe_7cecfa_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='spotify_user.spotifyuser')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_permissions', to='spotify_user.spotifyuser')),
            ],
            options={
                'db_table': 'chat_permissions',
                'indexes': [models.Index(fields=['requester', 'target'], name='chat_permis_request_6084b9_idx'), models.Index(fields=['is_accepted'], name='chat_permis_is_acce_e58e88_idx')],
                'unique_together': {('requester', 'target')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('music_link', models.URLField(blank=True, null=True)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_recalled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='spotify_user.spotifyuser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='spotify_user.spotifyuser')),
            ],
            options={
                'db_table': 'messages',
                'indexes': [models.Index(fields=['sender', 'receiver'], name='messages_sender__89e028_idx'), models.Index(fields=['is_pending'], name='messages_is_pend_db55ec_idx'), models.Index(fields=['created_at'], name='messages_created_919c58_idx')],
            },
        ),
    ]
