# Generated by Django 5.1.6 on 2025-04-26 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0002_alter_genre_table'),
        ('singer', '0005_alter_singersong_id_singer_alter_singersong_id_song'),
        ('song', '0006_song_file_audio_song_file_video_song_url_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('listen_date', models.DateTimeField()),
                ('play_duration', models.IntegerField(default=0)),
                ('listen_count', models.IntegerField(default=1)),
                ('id_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_history', to='genre.genre')),
                ('id_singer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singer_history', to='singer.singer')),
                ('id_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_history', to='song.song')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'history_history',
            },
        ),
    ]
