# Generated by Django 5.1.6 on 2025-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_song', models.BigIntegerField()),
                ('id_user', models.BigIntegerField()),
                ('listen_date', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
