# Generated by Django 5.1.6 on 2025-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_album', models.BigIntegerField()),
                ('id_song', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SingerAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_singer', models.BigIntegerField()),
                ('id_album', models.BigIntegerField()),
            ],
        ),
    ]
