# Generated by Django 5.1.6 on 2025-03-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album_album',
        ),
        migrations.AlterModelTable(
            name='albumsong',
            table='album_albumsong',
        ),
        migrations.AlterModelTable(
            name='singeralbum',
            table='album_singeralbum',
        ),
    ]
