# Generated by Django 5.1.6 on 2025-03-26 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_table_alter_albumsong_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumsong',
            old_name='id_album',
            new_name='id_album_id',
        ),
        migrations.RenameField(
            model_name='albumsong',
            old_name='id_song',
            new_name='id_song_id',
        ),
    ]
