# Generated by Django 5.1.6 on 2025-03-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_rename_id_album_albumsong_id_album_id_and_more'),
        ('singer', '0002_alter_singer_table_alter_singersong_table'),
        ('song', '0005_remove_song_id_genre_id_song_id_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumsong',
            name='id_album_id',
        ),
        migrations.RemoveField(
            model_name='albumsong',
            name='id_song_id',
        ),
        migrations.AddField(
            model_name='albumsong',
            name='id_album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='album.album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumsong',
            name='id_song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='song_albums', to='song.song'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albumsong',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='singeralbum',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='singeralbum',
            name='id_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_singers', to='album.album'),
        ),
        migrations.AlterField(
            model_name='singeralbum',
            name='id_singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_albums', to='singer.singer'),
        ),
    ]
