# Generated by Django 5.1.6 on 2025-04-21 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_albumsong_id_album_id_and_more'),
        ('singer', '0005_alter_singersong_id_singer_alter_singersong_id_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='id_singer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='singer.singer'),
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SingerAlbum',
        ),
    ]
