# Generated by Django 5.1.6 on 2025-04-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_album_id_singer_album_release_date_and_more'),
        ('song', '0006_song_file_audio_song_file_video_song_url_video'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albumsong',
            unique_together={('id_song',)},
        ),
    ]
