# Generated by Django 5.1.6 on 2025-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField()),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('id_user', models.BigIntegerField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_playlist', models.BigIntegerField()),
                ('id_song', models.BigIntegerField()),
            ],
        ),
    ]
