# Generated by Django 5.1.6 on 2025-03-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playlist',
            table='playlist_playlist',
        ),
        migrations.AlterModelTable(
            name='playlistsong',
            table='playlist_playlistsong',
        ),
    ]
