# Generated by Django 5.1.6 on 2025-03-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_alter_playlist_table_alter_playlistsong_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
