# Generated by Django 5.1.6 on 2025-03-25 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_alter_playlist_image'),
        ('song', '0004_rename_artist_song_image_rename_title_song_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsong',
            name='id_playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='playlist.playlist'),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='id_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_playlists', to='song.song'),
        ),
    ]
