# Generated by Django 5.1.6 on 2025-04-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_alter_playlist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistsong',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
