# Generated by Django 5.1.6 on 2025-04-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_playlistsong_date_added'),
        ('song', '0006_song_file_audio_song_file_video_song_url_video'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlistsong',
            unique_together={('id_playlist', 'id_song')},
        ),
    ]
