# Generated by Django 5.1.6 on 2025-04-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_playlistsong_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
