# Generated by Django 5.1.6 on 2025-04-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_alter_playlistsong_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
