# Generated by Django 5.1.6 on 2025-04-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_alter_playlist_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='create_date',
            field=models.DateField(),
        ),
    ]
