# Generated by Django 5.1.6 on 2025-04-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0009_alter_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsong',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
