# Generated by Django 5.1.6 on 2025-04-27 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0009_alter_playlist_create_date'),
        ('playlist', '0010_alter_playlistsong_date_added'),
    ]

    operations = [
    ]
