# Generated by Django 5.1.6 on 2025-04-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0010_alter_playlistsong_date_added'),
        ('spotify_user', '0018_merge_20250422_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='spotify_user.spotifyuser'),
        ),
    ]
