# Generated by Django 5.1.6 on 2025-04-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0009_alter_playlist_create_date'),
        ('playlist', '0011_alter_playlist_id_user'),
    ]

    operations = [
    ]
