# Generated by Django 5.1.6 on 2025-04-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0012_merge_20250428_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
