# Generated by Django 5.1.6 on 2025-05-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0011_merge_20250427_0941'),
        ('playlist', '0013_alter_playlist_image'),
    ]

    operations = [
    ]
