# Generated by Django 5.1.6 on 2025-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_id', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('vip', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.BigIntegerField()),
                ('id_album', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.BigIntegerField()),
                ('id_singer', models.BigIntegerField()),
            ],
        ),
    ]
