# Generated by Django 5.1.6 on 2025-03-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_song_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='image',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='popularity',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='song',
            name='id_genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='song',
            name='url_lyric',
        ),
        migrations.RemoveField(
            model_name='song',
            name='url_song',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
