# Generated by Django 5.1.6 on 2025-03-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_rename_image_song_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='duration',
            new_name='popularity',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='id_genre',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='song',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='song',
            name='url_lyric',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='url_song',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
