# Generated by Django 5.1.6 on 2025-03-26 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_alter_genre_table'),
        ('song', '0004_rename_artist_song_image_rename_title_song_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id_genre_id',
        ),
        migrations.AddField(
            model_name='song',
            name='id_genre',
            field=models.ForeignKey(db_column='id_genre_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='genre.genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='url_lyric',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='url_song',
            field=models.CharField(max_length=255),
        ),
    ]
