# Generated by Django 5.1.6 on 2025-04-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_song_file_audio_song_file_video_song_url_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_lyric',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='url_lyric',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
