# Generated by Django 5.1.6 on 2025-04-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_song_file_lyric_alter_song_url_lyric'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='url_song',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='url_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
