# Generated by Django 5.1.6 on 2025-05-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_song_is_vip_alter_song_url_song_alter_song_url_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='fingerprint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
