# Generated by Django 5.1.6 on 2025-03-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "RENAME TABLE user_user TO spotify_clone_spotifyuser;"  # Nếu bạn đổi tên khác
        ),
    ]
