# Generated by Django 5.1.6 on 2025-03-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0002_auto_20250312_1657'),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name='User',
        #     new_name='SpotifyUser',
        # ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_id', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('vip', models.BooleanField()),
            ],
            options={
                'db_table': 'user_user',
            },
        ),
        # Đánh dấu là không tạo bảng mới
        migrations.RunSQL(
            sql="SELECT 1;",  # Một câu lệnh rỗng để tránh lỗi
            reverse_sql="SELECT 1;",
        ),
        # migrations.DeleteModel(
        #     name='User',
        # ),
        migrations.AlterModelTable(
            name='useralbum',
            table='user_useralbum',
        ),
        migrations.AlterModelTable(
            name='usersinger',
            table='user_usersinger',
        ),
    ]
