# Generated by Django 5.1.6 on 2025-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0005_remove_spotifyuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='SpotifyUser',
            name='role',
            field=models.CharField( max_length=10, choices=[('user', 'User'), ('vip', 'VIP'), ('admin', 'Admin')], default='user'),
            preserve_default=False,
        ),
    ]
