# Generated by Django 5.1.6 on 2025-03-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0006_auto_20250315_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyuser',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='spotifyuser',
            name='role',
        ),
    ]
