# Generated by Django 5.1.6 on 2025-03-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0007_remove_spotifyuser_author_id_remove_spotifyuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='social_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
