# Generated by Django 5.1.6 on 2025-03-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0008_spotifyuser_provider_spotifyuser_social_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
