# Generated by Django 5.1.6 on 2025-03-23 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0009_alter_spotifyuser_email_alter_spotifyuser_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyuser',
            name='password',
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spotify_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
