# Generated by Django 5.1.6 on 2025-03-24 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0010_remove_spotifyuser_password_spotifyuser_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='provider',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('google', 'Google'), ('', 'None')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
