# Generated by Django 5.1.6 on 2025-03-27 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0011_spotifyuser_two_factor_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.BigIntegerField()),
                ('id_song', models.BigIntegerField()),
            ],
            options={
                'db_table': 'user_usersong',
                'unique_together': {('id_user', 'id_song')},
            },
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='spotify_user.spotifyuser')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='spotify_user.spotifyuser')),
            ],
            options={
                'db_table': 'user_following',
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
