# Generated by Django 5.1.6 on 2025-03-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0012_usersong_userfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='userfollowing',
            index=models.Index(fields=['follower', 'following'], name='user_follow_followe_7cecfa_idx'),
        ),
        migrations.AddIndex(
            model_name='userfollowing',
            index=models.Index(fields=['status'], name='user_follow_status_85319b_idx'),
        ),
    ]
