# Generated by Django 5.1.6 on 2025-04-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0012_usersong_userfollowing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersinger',
            unique_together={('id_user', 'id_singer')},
        ),
    ]
