# Generated by Django 5.1.6 on 2025-03-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0013_userfollowing_status_userfollowing_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userfollowing',
            name='user_follow_followe_7cecfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='userfollowing',
            name='user_follow_status_85319b_idx',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='updated_at',
        ),
    ]
