# Generated by Django 5.1.6 on 2025-04-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0013_alter_usersinger_unique_together'),
        ('spotify_user', '0014_remove_userfollowing_user_follow_followe_7cecfa_idx_and_more'),
    ]

    operations = [
    ]
