# Generated by Django 5.1.6 on 2025-04-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0015_merge_20250413_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='vip_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
