# Generated by Django 5.1.6 on 2025-04-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0015_merge_20250415_0811'),
        ('spotify_user', '0016_spotifyuser_vip_start_date'),
    ]

    operations = [
    ]
