# Generated by Django 5.1.6 on 2025-04-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_user', '0017_merge_20250421_1154'),
        ('spotify_user', '0017_merge_20250422_1313'),
        ('spotify_user', '0017_merge_20250422_1749'),
    ]

    operations = [
    ]
